version: "3.7"

services:
  spark-master:
    image: docker-spark-demo
    ports:
      - "8000:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/apps
      - ./data:/opt/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - spark-net

  spark-worker-1:
    image: docker-spark-demo
    volumes:
      - ./apps:/opt/apps
      - ./data:/opt/data
    ports:
      - "8001:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    networks:
      - spark-net

  spark-worker-2:
    image: docker-spark-demo
    volumes:
      - ./apps:/opt/apps
      - ./data:/opt/data
    ports:
      - "8002:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    networks:
      - spark-net

networks:
  spark-net:
